### ISSUE TITLE
建议：提供订阅方式

### ISSUE THREAD

**Issue by songkeys** [aliyunfe/weekly#2]
如果有 RSS 订阅就好了。

或者利用一下 GitHub 的 Watch Release Only，每周发布的同时发布一个 Release，大家也方便订阅。

⛽️

**Comment by answershuto** [comment]
@Songkeys 感谢你的建议，后面会考虑优化的哈～

**Comment by daijunooo** [comment]
感觉写的很好 ，💪

**Comment by xdlrt** [comment]
@Songkeys @daijunooo 已新增两种订阅方式~
